name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [main]
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  test-and-package:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up node 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: build and test
        run: |
          npm install
          npm run compile
          npm run test

      - name: package to vsix file
        run: npx vsce package -o dbt-language-server.vsix --baseImagesUrl=https://storage.googleapis.com/dbt-ls-images

      - name: create cache
        uses: actions/cache@v2
        with:
          path: |
            ./e2e
            ./dbt-language-server.vsix
          key: ${{ runner.os }}-cache-${{ github.sha}}

  run-e2e-tests:
    needs: test-and-package

    strategy:
      matrix:
        dbt-version: ['dbt==0.19.1', 'dbt']

    runs-on: macos-latest
    steps:
      - name: load e2e tests and vsix from cache
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ./e2e
            ./dbt-language-server.vsix
          key: ${{ runner.os }}-cache-${{ github.sha}}

      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - uses: actions/setup-python@v2
        with:
          python-version: '3.7.x'

      - run: mkdir -p ~/.dbt/ && cp ./e2e/profiles.yml ~/.dbt/profiles.yml
      - run: 'echo "$BQ_SERVICE_ACCOUNT" > ~/.dbt/bq-test-project.json'
        env:
          BQ_SERVICE_ACCOUNT: ${{ secrets.BQ_SERVICE_ACCOUNT }}
      - run: pip install ${{ matrix.dbt-version }}
      - run: dbt --version

      - run: unzip dbt-language-server.vsix -d e2e-tests
      - run: node e2e/out/runTest $(pwd)/e2e-tests/extension

  publish:
    needs: run-e2e-tests

    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up node 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: build
        run: |
          npm install
          npm run compile

      - id: vars
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "::set-output name=file_name::dbt-language-server-commit-sha-$(git rev-parse --short HEAD).vsix"

      - name: package to vsix file
        if: ${{ github.ref == 'refs/heads/main' }}
        run: npx vsce package -o ${{ steps.vars.outputs.file_name }} --baseImagesUrl=https://storage.googleapis.com/dbt-ls-images

      - name: push to GCS
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: google-github-actions/upload-cloud-storage@main
        with:
          path: ${{ steps.vars.outputs.file_name }}
          destination: dbt-language-server
          credentials: ${{ secrets.GCS_SERVICE_ACCOUNT }}

      - name: publish tagged (latest) extension
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: npx vsce ls --baseImagesUrl=https://storage.googleapis.com/dbt-ls-images
